### ISSUE TITLE
Use timeago.js can save a lot of bits

### ISSUE THREAD

**Issue by hustcc** [TylerLH/react-native-timeago#10]
Calculate the timeago of date, it has used `moment` library, and only use one API of moment.

if Replace it with [timeago.js](https://github.com/hustcc/timeago.js) (only 2kb), can save a lot of file size.

Maybe you can consider for this. ^_^

**Comment by TylerLH** [comment]
Thanks for the suggestion. I'll consider it, but IMO the savings in this scenario are negligible since moment.js would account for <100kb of a compiled app's size (an average of ~23mb as of 2012). If this were for web, I'd definitely agree that a switch would be warranted. I'm just not convinced there's a significant advantage in a native app context.
